/**
 * INRT WALLET — TermsAndConditions.tsx
 * Add route in App.tsx: <Route path="/terms" element={<TermsAndConditions />} />
 */

import { useNavigate } from 'react-router-dom';

export default function TermsAndConditions() {
  const navigate = useNavigate();

  const sections = [
    {
      title: '1. Acceptance of Terms',
      content: [
        { sub: '1.1 Agreement', text: 'By downloading, installing, accessing, or using the INRT Wallet application ("App") or website inrtwallet.in ("Platform"), you agree to be bound by these Terms and Conditions ("Terms"). If you do not agree, do not use the Platform.' },
        { sub: '1.2 Eligibility', text: 'You must be at least 18 years of age and a resident of India to use INRT Wallet. By using the App, you represent that you meet these requirements.' },
        { sub: '1.3 Updates', text: 'We reserve the right to modify these Terms at any time. Continued use after changes constitutes acceptance. We will notify you of material changes via the App or email.' },
      ],
    },
    {
      title: '2. Our Services',
      content: [
        { sub: '2.1 Wallet Services', text: 'INRT Wallet provides a digital wallet that allows you to store funds, make payments, transfer money to other users, pay bills, recharge mobile numbers, and perform other financial transactions within the limits set by applicable regulations.' },
        { sub: '2.2 INRT Token', text: 'INRT is a utility token pegged at 1 INRT = ₹1 (Indian Rupee). It can be used for payments within the app and for cross-border transactions. INRT is not a currency, security, or investment product. Its value is maintained by INRT Wallet as a stablecoin.' },
        { sub: '2.3 Service Availability', text: 'We do not guarantee uninterrupted availability. The Platform may be unavailable during maintenance, upgrades, or due to circumstances beyond our control including bank outages, NPCI downtime, or regulatory orders.' },
        { sub: '2.4 Transaction Limits', text: 'Without KYC: Maximum ₹10,000 per day. With verified KYC: Maximum ₹1,00,000 per day. These limits may be changed in accordance with RBI regulations.' },
      ],
    },
    {
      title: '3. Account Registration & KYC',
      content: [
        { sub: '3.1 Account Creation', text: 'You must provide accurate, current, and complete information during registration. You are responsible for maintaining the confidentiality of your login credentials and for all activities under your account.' },
        { sub: '3.2 KYC Requirements', text: 'As per RBI guidelines, full wallet services require KYC verification using your Aadhaar and PAN. By submitting KYC documents, you consent to verification with UIDAI, Income Tax Department, and our KYC partners.' },
        { sub: '3.3 One Account Per Person', text: 'You may only maintain one active account. Creating multiple accounts using the same identity documents is prohibited and may result in immediate account termination and reporting to authorities.' },
        { sub: '3.4 Account Security', text: 'You must immediately notify us at support@inrtwallet.in if you suspect unauthorized access to your account. We are not liable for losses resulting from unauthorized access caused by your failure to secure your credentials.' },
      ],
    },
    {
      title: '4. Payments & Transactions',
      content: [
        { sub: '4.1 Transaction Finality', text: 'Once a payment transaction is initiated and confirmed, it cannot be reversed except as provided in our Refund Policy. Always verify recipient details before confirming any transaction.' },
        { sub: '4.2 Failed Transactions', text: 'If a transaction fails after funds are debited from your wallet, the amount will be credited back within 3-5 business days. For recharges, if the service provider fails to deliver, refunds will be processed as per our Refund Policy.' },
        { sub: '4.3 Transaction Records', text: 'Electronic transaction records generated by INRT Wallet shall be final and binding. You should regularly review your transaction history and report discrepancies within 7 days.' },
        { sub: '4.4 Prohibited Transactions', text: 'You may not use INRT Wallet for illegal activities, money laundering, terrorist financing, gambling, purchase of prohibited goods, or any activity that violates applicable Indian law including FEMA and PMLA.' },
      ],
    },
    {
      title: '5. Fees & Charges',
      content: [
        { sub: '5.1 Current Fee Structure', text: 'Wallet-to-wallet transfers: Free\nMobile recharges: Free (commissions earned from operators)\nBill payments: Free (commissions earned from billers)\nCross-border INRT payments: Free\nWithdrawal to bank: ₹0 (subject to change)' },
        { sub: '5.2 Fee Changes', text: 'We reserve the right to introduce or modify fees with 7 days prior notice. Continued use after fee changes constitutes acceptance.' },
        { sub: '5.3 Third-Party Charges', text: 'Your bank may charge fees for loading money into your wallet. We are not responsible for charges levied by your bank or payment processor.' },
      ],
    },
    {
      title: '6. INRT Token Terms',
      content: [
        { sub: '6.1 Not a Security', text: 'INRT tokens do not represent equity, debt, or ownership interest in INRT Wallet or any entity. Holding INRT does not entitle you to dividends, profits, or voting rights.' },
        { sub: '6.2 Stablecoin Peg', text: 'While we maintain the 1 INRT = ₹1 peg on a best-effort basis, we cannot guarantee this peg under all market conditions. We are not liable for losses arising from any deviation.' },
        { sub: '6.3 Tax Obligations', text: 'You are solely responsible for any tax obligations arising from INRT transactions including 30% tax on gains and applicable TDS under Section 194S of the Income Tax Act, 1961.' },
        { sub: '6.4 Regulatory Risk', text: 'Cryptocurrency regulations in India are evolving. We may be required to modify, suspend, or terminate INRT services to comply with regulatory changes. We are not liable for losses arising from such regulatory changes.' },
      ],
    },
    {
      title: '7. Prohibited Activities',
      content: [
        { sub: '7.1 You May Not:', text: '• Use the Platform for any unlawful purpose\n• Conduct fraudulent transactions or impersonate another person\n• Attempt to hack, disrupt, or damage the Platform\n• Use automated bots or scripts to access the Platform\n• Circumvent transaction limits or KYC requirements\n• Use INRT Wallet to evade taxes or launder money\n• Resell or transfer your account to another person' },
      ],
    },
    {
      title: '8. Intellectual Property',
      content: [
        { sub: '8.1 Our Property', text: 'All content on the Platform including logos, designs, text, graphics, software, and the INRT brand are owned by or licensed to INRT Wallet. You may not copy, modify, distribute, or create derivative works without our written consent.' },
        { sub: '8.2 Your License', text: 'We grant you a limited, non-exclusive, non-transferable license to use the App for personal, non-commercial purposes in accordance with these Terms.' },
      ],
    },
    {
      title: '9. Limitation of Liability',
      content: [
        { sub: '9.1 No Indirect Damages', text: 'To the maximum extent permitted by law, INRT Wallet shall not be liable for indirect, incidental, special, consequential, or punitive damages including lost profits, data loss, or business interruption.' },
        { sub: '9.2 Maximum Liability', text: 'Our total liability for any claim shall not exceed the amount of the disputed transaction or ₹10,000, whichever is lower.' },
        { sub: '9.3 Force Majeure', text: 'We are not liable for failures caused by events beyond our control including natural disasters, government orders, bank/NPCI failures, internet outages, or cyberattacks.' },
      ],
    },
    {
      title: '10. Dispute Resolution',
      content: [
        { sub: '10.1 Grievance Redressal', text: 'For complaints, contact our Grievance Officer:\nEmail: grievance@inrtwallet.in\nResponse time: 30 days' },
        { sub: '10.2 Governing Law', text: 'These Terms are governed by the laws of India. Any disputes shall be subject to the exclusive jurisdiction of courts in India.' },
        { sub: '10.3 Arbitration', text: 'Disputes may be resolved through arbitration under the Arbitration and Conciliation Act, 1996, by a sole arbitrator appointed by INRT Wallet.' },
      ],
    },
    {
      title: '11. Termination',
      content: [
        { sub: '11.1 By You', text: 'You may close your account at any time by contacting support@inrtwallet.in. Any remaining wallet balance will be refunded to your registered bank account within 5-7 business days.' },
        { sub: '11.2 By Us', text: 'We may suspend or terminate your account without notice if you violate these Terms, engage in fraudulent activity, or if required by law or regulatory authority.' },
      ],
    },
    {
      title: '12. Contact Information',
      content: [
        { sub: 'INRT Wallet Support', text: 'Email: support@inrtwallet.in\nGrievance: grievance@inrtwallet.in\nWebsite: inrtwallet.in\n\nFor regulatory queries:\nCompliance Officer\nEmail: compliance@inrtwallet.in' },
      ],
    },
  ];

  return (
    <div style={S.page}>
      <div style={S.header}>
        <button onClick={() => navigate(-1)} style={S.backBtn}>←</button>
        <h1 style={S.headerTitle}>Terms & Conditions</h1>
      </div>

      <div style={S.body}>
        <div style={S.introCard}>
          <p style={S.introTitle}>📋 Please Read Carefully</p>
          <p style={S.introText}>
            These Terms and Conditions govern your use of INRT Wallet. By using our services, you agree to be bound by these Terms.
          </p>
          <p style={S.introText}>
            <strong style={{ color: '#fff' }}>Effective Date:</strong> {new Date().toLocaleDateString('en-IN', { day: 'numeric', month: 'long', year: 'numeric' })}
          </p>
          <p style={{ ...S.introText, margin: 0 }}>
            <strong style={{ color: '#fff' }}>Operated by:</strong> INRT Wallet · inrtwallet.in
          </p>
        </div>

        {sections.map((section, i) => (
          <div key={i} style={S.section}>
            <h2 style={S.sectionTitle}>{section.title}</h2>
            {section.content.map((item, j) => (
              <div key={j} style={S.item}>
                <p style={S.itemSub}>{item.sub}</p>
                <p style={S.itemText}>{item.text}</p>
              </div>
            ))}
          </div>
        ))}

        <div style={S.footerCard}>
          <p style={{ color: 'rgba(255,255,255,0.4)', fontSize: 12, textAlign: 'center', margin: 0, lineHeight: 1.7 }}>
            By using INRT Wallet, you confirm that you have read, understood, and agree to these Terms and Conditions.
            These Terms are governed by the laws of India.
          </p>
        </div>
      </div>
    </div>
  );
}

const S: Record<string, React.CSSProperties> = {
  page:        { maxWidth: 480, margin: '0 auto', minHeight: '100vh', background: '#050914', fontFamily: "'Plus Jakarta Sans',sans-serif" },
  header:      { background: 'linear-gradient(160deg,#050914,#0a1428)', padding: '52px 20px 20px', display: 'flex', alignItems: 'center', gap: 14, position: 'sticky', top: 0, zIndex: 100, borderBottom: '1px solid rgba(255,255,255,0.06)' },
  backBtn:     { background: 'none', border: 'none', color: '#00e5cc', fontSize: 22, cursor: 'pointer', lineHeight: 1, flexShrink: 0 },
  headerTitle: { fontFamily: "'Plus Jakarta Sans',sans-serif", fontWeight: 800, fontSize: 20, color: '#fff', margin: 0 },
  body:        { padding: '16px 16px 60px' },
  introCard:   { background: 'linear-gradient(135deg,rgba(0,229,204,0.08),rgba(0,112,243,0.08))', border: '1px solid rgba(0,229,204,0.15)', borderRadius: 18, padding: '20px 18px', marginBottom: 20 },
  introTitle:  { fontFamily: "'Plus Jakarta Sans',sans-serif", fontWeight: 800, fontSize: 16, color: '#fff', margin: '0 0 10px' },
  introText:   { color: 'rgba(255,255,255,0.55)', fontSize: 13, margin: '0 0 8px', lineHeight: 1.7 },
  section:     { background: 'rgba(255,255,255,0.03)', border: '1px solid rgba(255,255,255,0.07)', borderRadius: 16, padding: '18px 16px', marginBottom: 12 },
  sectionTitle:{ fontFamily: "'Plus Jakarta Sans',sans-serif", fontWeight: 800, fontSize: 15, color: '#00e5cc', margin: '0 0 14px' },
  item:        { marginBottom: 14, paddingBottom: 14, borderBottom: '1px solid rgba(255,255,255,0.05)' },
  itemSub:     { fontFamily: "'Plus Jakarta Sans',sans-serif", fontWeight: 700, fontSize: 13, color: '#fff', margin: '0 0 6px' },
  itemText:    { color: 'rgba(255,255,255,0.5)', fontSize: 13, margin: 0, lineHeight: 1.8, whiteSpace: 'pre-line' as const },
  footerCard:  { background: 'rgba(255,255,255,0.02)', border: '1px solid rgba(255,255,255,0.05)', borderRadius: 14, padding: '16px', marginTop: 8 },
};
